{% set name = "data-science-types" %}
{% set version = "0.2.22" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/predictive-analytics-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 89b3c3f742303e1922488ebc02b9660d1db55d8f80f5c49f87977f1c1a4572c2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/data-science-types/
  summary: Type stubs for Python machine learning libraries
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/predictive-analytics-lab/data-science-types

extra:
  recipe-maintainers:
    - ickc
