{% set name = "data-science-types" %}
{% set version = "0.2.22" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/data-science-types-{{ version }}.tar.gz
  sha256: 5b6bb2ca4cb6b8c467c799382e12156816f38122522bdaafd882d5a3828c7345

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/data-science-types/
  summary: Type stubs for Python machine learning libraries
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/predictive-analytics-lab/data-science-types

extra:
  recipe-maintainers:
    - ickc
